// Generated by gencpp from file object_detection_speech/CaptureResponse.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURERESPONSE_H
#define OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detection_speech
{
template <class ContainerAllocator>
struct CaptureResponse_
{
  typedef CaptureResponse_<ContainerAllocator> Type;

  CaptureResponse_()
    : res(false)  {
    }
  CaptureResponse_(const ContainerAllocator& _alloc)
    : res(false)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::object_detection_speech::CaptureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection_speech::CaptureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CaptureResponse_

typedef ::object_detection_speech::CaptureResponse_<std::allocator<void> > CaptureResponse;

typedef boost::shared_ptr< ::object_detection_speech::CaptureResponse > CaptureResponsePtr;
typedef boost::shared_ptr< ::object_detection_speech::CaptureResponse const> CaptureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection_speech::CaptureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detection_speech

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'object_detection_speech': ['/home/mivia/cog2020_group11/src/object_detection_speech/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_speech::CaptureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_speech::CaptureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_speech::CaptureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e27848a10f8e7e4030443887dfea101b";
  }

  static const char* value(const ::object_detection_speech::CaptureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe27848a10f8e7e40ULL;
  static const uint64_t static_value2 = 0x30443887dfea101bULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection_speech/CaptureResponse";
  }

  static const char* value(const ::object_detection_speech::CaptureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool res\n\
";
  }

  static const char* value(const ::object_detection_speech::CaptureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CaptureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection_speech::CaptureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_detection_speech::CaptureResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURERESPONSE_H
