// Generated by gencpp from file object_detection_speech/capture_ended.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURE_ENDED_H
#define OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURE_ENDED_H

#include <ros/service_traits.h>


#include <object_detection_speech/capture_endedRequest.h>
#include <object_detection_speech/capture_endedResponse.h>


namespace object_detection_speech
{

struct capture_ended
{

typedef capture_endedRequest Request;
typedef capture_endedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct capture_ended
} // namespace object_detection_speech


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_detection_speech::capture_ended > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::object_detection_speech::capture_ended&) { return value(); }
};

template<>
struct DataType< ::object_detection_speech::capture_ended > {
  static const char* value()
  {
    return "object_detection_speech/capture_ended";
  }

  static const char* value(const ::object_detection_speech::capture_ended&) { return value(); }
};


// service_traits::MD5Sum< ::object_detection_speech::capture_endedRequest> should match 
// service_traits::MD5Sum< ::object_detection_speech::capture_ended > 
template<>
struct MD5Sum< ::object_detection_speech::capture_endedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_detection_speech::capture_ended >::value();
  }
  static const char* value(const ::object_detection_speech::capture_endedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detection_speech::capture_endedRequest> should match 
// service_traits::DataType< ::object_detection_speech::capture_ended > 
template<>
struct DataType< ::object_detection_speech::capture_endedRequest>
{
  static const char* value()
  {
    return DataType< ::object_detection_speech::capture_ended >::value();
  }
  static const char* value(const ::object_detection_speech::capture_endedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_detection_speech::capture_endedResponse> should match 
// service_traits::MD5Sum< ::object_detection_speech::capture_ended > 
template<>
struct MD5Sum< ::object_detection_speech::capture_endedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_detection_speech::capture_ended >::value();
  }
  static const char* value(const ::object_detection_speech::capture_endedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detection_speech::capture_endedResponse> should match 
// service_traits::DataType< ::object_detection_speech::capture_ended > 
template<>
struct DataType< ::object_detection_speech::capture_endedResponse>
{
  static const char* value()
  {
    return DataType< ::object_detection_speech::capture_ended >::value();
  }
  static const char* value(const ::object_detection_speech::capture_endedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURE_ENDED_H
