// Generated by gencpp from file object_detection_speech/capture_endedRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURE_ENDEDREQUEST_H
#define OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURE_ENDEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_detection_speech
{
template <class ContainerAllocator>
struct capture_endedRequest_
{
  typedef capture_endedRequest_<ContainerAllocator> Type;

  capture_endedRequest_()
    {
    }
  capture_endedRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct capture_endedRequest_

typedef ::object_detection_speech::capture_endedRequest_<std::allocator<void> > capture_endedRequest;

typedef boost::shared_ptr< ::object_detection_speech::capture_endedRequest > capture_endedRequestPtr;
typedef boost::shared_ptr< ::object_detection_speech::capture_endedRequest const> capture_endedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_detection_speech::capture_endedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace object_detection_speech

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::object_detection_speech::capture_endedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_detection_speech/capture_endedRequest";
  }

  static const char* value(const ::object_detection_speech::capture_endedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::object_detection_speech::capture_endedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct capture_endedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_detection_speech::capture_endedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::object_detection_speech::capture_endedRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_DETECTION_SPEECH_MESSAGE_CAPTURE_ENDEDREQUEST_H
