// Generated by gencpp from file object_detection_speech/Say.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTION_SPEECH_MESSAGE_SAY_H
#define OBJECT_DETECTION_SPEECH_MESSAGE_SAY_H

#include <ros/service_traits.h>


#include <object_detection_speech/SayRequest.h>
#include <object_detection_speech/SayResponse.h>


namespace object_detection_speech
{

struct Say
{

typedef SayRequest Request;
typedef SayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Say
} // namespace object_detection_speech


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_detection_speech::Say > {
  static const char* value()
  {
    return "744b6fa2f5c40325431e2e62fe3a175f";
  }

  static const char* value(const ::object_detection_speech::Say&) { return value(); }
};

template<>
struct DataType< ::object_detection_speech::Say > {
  static const char* value()
  {
    return "object_detection_speech/Say";
  }

  static const char* value(const ::object_detection_speech::Say&) { return value(); }
};


// service_traits::MD5Sum< ::object_detection_speech::SayRequest> should match 
// service_traits::MD5Sum< ::object_detection_speech::Say > 
template<>
struct MD5Sum< ::object_detection_speech::SayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_detection_speech::Say >::value();
  }
  static const char* value(const ::object_detection_speech::SayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detection_speech::SayRequest> should match 
// service_traits::DataType< ::object_detection_speech::Say > 
template<>
struct DataType< ::object_detection_speech::SayRequest>
{
  static const char* value()
  {
    return DataType< ::object_detection_speech::Say >::value();
  }
  static const char* value(const ::object_detection_speech::SayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_detection_speech::SayResponse> should match 
// service_traits::MD5Sum< ::object_detection_speech::Say > 
template<>
struct MD5Sum< ::object_detection_speech::SayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_detection_speech::Say >::value();
  }
  static const char* value(const ::object_detection_speech::SayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detection_speech::SayResponse> should match 
// service_traits::DataType< ::object_detection_speech::Say > 
template<>
struct DataType< ::object_detection_speech::SayResponse>
{
  static const char* value()
  {
    return DataType< ::object_detection_speech::Say >::value();
  }
  static const char* value(const ::object_detection_speech::SayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_DETECTION_SPEECH_MESSAGE_SAY_H
